language: csharp
mono: none
dotnet: 5.0
solution: webapp_DataTransferToView.sln
branches: 
  only:
    - master
    - main

install: 
  - dotnet restore

before_script:
  - chmod -R a+x scripts
  - ./scripts/begin.sh
  
script:  
  - ./scripts/current.sh

after_script:
  - ./scripts/end.sh

notification:
  email:
    on_success: always
    on_failure: always